name: Build with qmake
on: 
  workflow_call:
    inputs:
      qmakeflags:
        required: false
        type: string     
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build 
      run: /usr/bin/qmake VolanteAlphaQT.pro ${{ inputs.qmakeflags }} && make