name: Install QT6
on:
  workflow_call:
    inputs:
      extras:
        required: false
        type: string
jobs: 
  install-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install qt6-base-dev qt5-qmake qtbase5-dev libqt6serialport6 libqt6serialport6-dev libqt5serialport5 libqt5serialport5-dev nlohmann-json3-dev ${{ inputs.extras }}
    