name: Install QT6
on:
  workflow_call:
    inputs:
      extras:
        required: false
        type: string
jobs: 
  execution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install qt6-base-dev ${{ inputs.extras }}
    