name: Test the binary.
on:
  workflow_call:
    inputs:
      suite: 
        required: false
        type: string
jobs: 
  install-qt-desktop:
    uses: ./.github/workflows/installQTdesktop_wf.yml
    with:
      extras: "gengetopt socat"
  build-qt-desktop:
    needs: install-qt-desktop
    uses: ./.github/workflows/buildQmake_wf.yml
    with:
      qmakeflags: "CONFIG+=test"
  test-qt-desktop:
    needs: [install-qt-desktop, build-qt-desktop]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch artifacts from build-qt-desktop
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: buildQmake_wf.yml
          run_id: ${{ needs.build-qt-desktop.runs.id }}
          name: VolanteAlphaQT
          path: $GITHUB_WORKSPACE
      
      - name: Run tests
        run: cd $GITHUB_WORKSPACE && ./bin/VolanteAlphaQT_testes -platform offscreen
  
    
