name: Test the binary.
on:
  workflow_call:
    inputs:
      suite: 
        required: false
        type: string
jobs: 
  install-qt-desktop:
    uses: ./.github/workflows/installQTdesktop_wf.yml
    with:
      extras: "qt6-qmake qtbase6-dev-tools"
  clone-repo: 
    uses: ./.github/workflows/cloneRepo_wf.yml
  build-test:
    needs: [install-qt-desktop, clone-repo]
    uses: ./.github/workflows/buildQmake_wf.yml
    with:
      qmakeflags: "CONFIG+=test"
  test:
    needs: [install-qt-desktop, clone-repo, build-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./bin/VolanteAlphaQT_test

    
    
